const NAKSHATRAS = [
  { name:'Ashwini', hindi:'अश्विनी', range:'0°–13°20\' Aries', ruler:'Ketu', deity:'Ashwini Kumars', symbol:'Horse Head', traits:'Quick, energetic, healing ability, adventurous', lucky:{ color:'Red', stone:'Cat\'s Eye', number:9 }, career:'Doctor, athlete, entrepreneur', mantra:'Om Ashwinibhyam Namah' },
  { name:'Bharani', hindi:'भरणी', range:'13°20\'–26°40\' Aries', ruler:'Venus', deity:'Yama', symbol:'Yoni', traits:'Determined, creative, restless, strong-willed', lucky:{ color:'Red', stone:'Diamond', number:6 }, career:'Artist, entertainer, law', mantra:'Om Yamaya Namah' },
  { name:'Krittika', hindi:'कृत्तिका', range:'26°40\' Aries–10° Taurus', ruler:'Sun', deity:'Agni', symbol:'Razor/Flame', traits:'Sharp, ambitious, determined, leadership', lucky:{ color:'White', stone:'Ruby', number:1 }, career:'Military, surgery, politics', mantra:'Om Agnaye Namah' },
  { name:'Rohini', hindi:'रोहिणी', range:'10°–23°20\' Taurus', ruler:'Moon', deity:'Brahma', symbol:'Cart/Ox', traits:'Beautiful, sensual, creative, charismatic', lucky:{ color:'White', stone:'Pearl', number:2 }, career:'Arts, fashion, agriculture, business', mantra:'Om Brahmane Namah' },
  { name:'Mrigashira', hindi:'मृगशिरा', range:'23°20\' Taurus–6°40\' Gemini', ruler:'Mars', deity:'Soma', symbol:'Deer Head', traits:'Gentle, curious, searching, creative', lucky:{ color:'Silver', stone:'Red Coral', number:9 }, career:'Research, writing, travel', mantra:'Om Somaya Namah' },
  { name:'Ardra', hindi:'आर्द्रा', range:'6°40\'–20° Gemini', ruler:'Rahu', deity:'Rudra', symbol:'Teardrop', traits:'Intense, transformative, sharp mind, emotional', lucky:{ color:'Green', stone:'Hessonite', number:4 }, career:'Science, engineering, politics', mantra:'Om Rudraya Namah' },
  { name:'Punarvasu', hindi:'पुनर्वसु', range:'20° Gemini–3°20\' Cancer', ruler:'Jupiter', deity:'Aditi', symbol:'Bow & Quiver', traits:'Kind, philosophical, optimistic, spiritual', lucky:{ color:'Yellow', stone:'Yellow Sapphire', number:3 }, career:'Teaching, philosophy, healing', mantra:'Om Aditaye Namah' },
  { name:'Pushya', hindi:'पुष्य', range:'3°20\'–16°40\' Cancer', ruler:'Saturn', deity:'Brihaspati', symbol:'Lotus/Udder', traits:'Nurturing, caring, spiritual, protective', lucky:{ color:'Red', stone:'Blue Sapphire', number:8 }, career:'Spiritual work, nursing, food', mantra:'Om Brihaspataye Namah' },
  { name:'Ashlesha', hindi:'आश्लेषा', range:'16°40\'–30° Cancer', ruler:'Mercury', deity:'Nagas', symbol:'Serpent', traits:'Mystical, perceptive, cunning, healing', lucky:{ color:'Black/Red', stone:'Emerald', number:5 }, career:'Psychology, healing, occult', mantra:'Om Nagabhyam Namah' },
  { name:'Magha', hindi:'मघा', range:'0°–13°20\' Leo', ruler:'Ketu', deity:'Pitras', symbol:'Royal Throne', traits:'Regal, ambitious, proud, ancestral connection', lucky:{ color:'Ivory', stone:'Cat\'s Eye', number:1 }, career:'Politics, leadership, business', mantra:'Om Pitribhyah Namah' },
  { name:'Purva Phalguni', hindi:'पूर्वाफाल्गुनी', range:'13°20\'–26°40\' Leo', ruler:'Venus', deity:'Bhaga', symbol:'Swing', traits:'Creative, pleasure-loving, romantic, generous', lucky:{ color:'Light Pink', stone:'Diamond', number:6 }, career:'Arts, entertainment, luxury', mantra:'Om Bhagaya Namah' },
  { name:'Uttara Phalguni', hindi:'उत्तराफाल्गुनी', range:'26°40\' Leo–10° Virgo', ruler:'Sun', deity:'Aryaman', symbol:'Bed/Hammock', traits:'Responsible, generous, stable, helpful', lucky:{ color:'Bright Blue', stone:'Ruby', number:1 }, career:'Management, social work, medicine', mantra:'Om Aryamanaya Namah' },
  { name:'Hasta', hindi:'हस्त', range:'10°–23°20\' Virgo', ruler:'Moon', deity:'Savitar', symbol:'Hand', traits:'Skillful, charming, hardworking, crafty', lucky:{ color:'Deep Green', stone:'Pearl', number:2 }, career:'Crafts, healing, finance, writing', mantra:'Om Savitre Namah' },
  { name:'Chitra', hindi:'चित्रा', range:'23°20\' Virgo–6°40\' Libra', ruler:'Mars', deity:'Vishwakarma', symbol:'Pearl/Gem', traits:'Artistic, brilliant, glamorous, charming', lucky:{ color:'Black', stone:'Red Coral', number:9 }, career:'Architecture, design, arts', mantra:'Om Vishwakarmane Namah' },
  { name:'Swati', hindi:'स्वाति', range:'6°40\'–20° Libra', ruler:'Rahu', deity:'Vayu', symbol:'Sword/Coral', traits:'Independent, flexible, diplomatic, business-minded', lucky:{ color:'Black', stone:'Hessonite', number:4 }, career:'Business, trade, diplomacy', mantra:'Om Vayave Namah' },
  { name:'Vishakha', hindi:'विशाखा', range:'20° Libra–3°20\' Scorpio', ruler:'Jupiter', deity:'Indra-Agni', symbol:'Arch/Potter\'s Wheel', traits:'Ambitious, competitive, purposeful, fiery', lucky:{ color:'Golden', stone:'Yellow Sapphire', number:3 }, career:'Politics, business, law', mantra:'Om Indragninabhyam Namah' },
  { name:'Anuradha', hindi:'अनुराधा', range:'3°20\'–16°40\' Scorpio', ruler:'Saturn', deity:'Mitra', symbol:'Lotus', traits:'Devoted, friendly, spiritual, organized', lucky:{ color:'Reddish Brown', stone:'Blue Sapphire', number:8 }, career:'Management, occult, teamwork', mantra:'Om Mitraya Namah' },
  { name:'Jyeshtha', hindi:'ज्येष्ठा', range:'16°40\'–30° Scorpio', ruler:'Mercury', deity:'Indra', symbol:'Circular Amulet', traits:'Protective, senior, responsible, intense', lucky:{ color:'Cream', stone:'Emerald', number:5 }, career:'Military, leadership, occult', mantra:'Om Indraya Namah' },
  { name:'Mula', hindi:'मूल', range:'0°–13°20\' Sagittarius', ruler:'Ketu', deity:'Nirriti', symbol:'Root Bundle', traits:'Investigative, philosophical, transformative', lucky:{ color:'Brown/Yellow', stone:'Cat\'s Eye', number:7 }, career:'Research, healing, philosophy', mantra:'Om Nirritaye Namah' },
  { name:'Purva Ashadha', hindi:'पूर्वाषाढा', range:'13°20\'–26°40\' Sagittarius', ruler:'Venus', deity:'Apas', symbol:'Winnowing Fan', traits:'Invincible, proud, ambitious, eloquent', lucky:{ color:'Black', stone:'Diamond', number:6 }, career:'Politics, law, arts, travel', mantra:'Om Adbhyoh Namah' },
  { name:'Uttara Ashadha', hindi:'उत्तराषाढा', range:'26°40\' Sagittarius–10° Capricorn', ruler:'Sun', deity:'Vishwadevas', symbol:'Elephant Tusk', traits:'Noble, sincere, responsible, victorious', lucky:{ color:'Copper', stone:'Ruby', number:1 }, career:'Leadership, law, government', mantra:'Om Vishwadevebhyoh Namah' },
  { name:'Shravana', hindi:'श्रवण', range:'10°–23°20\' Capricorn', ruler:'Moon', deity:'Vishnu', symbol:'Ear/Arrow', traits:'Learning, listening, scholarly, spiritual', lucky:{ color:'Light Blue', stone:'Pearl', number:2 }, career:'Education, media, counseling', mantra:'Om Vishnave Namah' },
  { name:'Dhanishtha', hindi:'धनिष्ठा', range:'23°20\' Capricorn–6°40\' Aquarius', ruler:'Mars', deity:'Ashta Vasus', symbol:'Drum/Flute', traits:'Musical, courageous, ambitious, generous', lucky:{ color:'Silver/Gray', stone:'Red Coral', number:8 }, career:'Music, military, real estate', mantra:'Om Vasubhyoh Namah' },
  { name:'Shatabhisha', hindi:'शतभिषा', range:'6°40\'–20° Aquarius', ruler:'Rahu', deity:'Varuna', symbol:'Empty Circle', traits:'Mysterious, healing, philosophical, independent', lucky:{ color:'Blue/Green', stone:'Hessonite', number:4 }, career:'Medicine, science, occult', mantra:'Om Varunaya Namah' },
  { name:'Purva Bhadrapada', hindi:'पूर्वभाद्रपदा', range:'20° Aquarius–3°20\' Pisces', ruler:'Jupiter', deity:'Aja Ekapada', symbol:'Swords/Two Faces', traits:'Passionate, unconventional, intense, transformative', lucky:{ color:'Silver', stone:'Yellow Sapphire', number:3 }, career:'Occult, research, entrepreneurship', mantra:'Om Ajapadaya Namah' },
  { name:'Uttara Bhadrapada', hindi:'उत्तरभाद्रपदा', range:'3°20\'–16°40\' Pisces', ruler:'Saturn', deity:'Ahir Budhnya', symbol:'Funeral Cot', traits:'Wise, deeply spiritual, patient, charitable', lucky:{ color:'Purple', stone:'Blue Sapphire', number:8 }, career:'Spirituality, healing, counseling', mantra:'Om Ahirbudhnyaya Namah' },
  { name:'Revati', hindi:'रेवती', range:'16°40\'–30° Pisces', ruler:'Mercury', deity:'Pushan', symbol:'Fish/Drum', traits:'Protective, nurturing, artistic, spiritual', lucky:{ color:'Brown', stone:'Emerald', number:5 }, career:'Arts, travel, spiritual work', mantra:'Om Pushnaye Namah' },
];

function getNakshatraByDob(dob) {
  // Simplified: map birth month+day to nakshatra index
  const d = new Date(dob);
  const dayOfYear = Math.floor((d - new Date(d.getFullYear(), 0, 0)) / 86400000);
  const idx = Math.floor((dayOfYear / 365) * 27);
  return NAKSHATRAS[idx % 27];
}

module.exports = { getNakshatraByDob, NAKSHATRAS };
