// Puja Guide — step-by-step puja instructions, no API needed

const PUJA_GUIDES = {
  ganesh: {
    name: 'Ganesh Puja',
    deity: 'Lord Ganesha',
    icon: '🐘',
    purpose: 'Remove obstacles, new beginnings, success in work and studies',
    bestDay: 'Wednesday & Chaturthi (4th day of lunar month)',
    duration: '15–30 minutes',
    items: [
      'Ganesh idol or photo',
      'Red flowers (especially Hibiscus)',
      'Modak or Ladoo (sweet)',
      'Durva grass (3 or 5 blades)',
      'Sindoor (vermillion)',
      'Incense sticks',
      'Diya (oil lamp)',
      'Panchamrit (milk, curd, honey, sugar, ghee)',
      'Coconut',
      'Janeu (sacred thread)'
    ],
    steps: [
      '🛁 Purify yourself — take bath, wear clean clothes',
      '🪑 Sit facing East or North',
      '🌸 Place Ganesh idol on a clean cloth or altar',
      '💧 Sprinkle Ganga Jal to purify the idol',
      '🥛 Perform Panchamrit Abhishek — pour milk, curd, honey, sugar, ghee on idol',
      '🚿 Clean idol with water and wipe dry',
      '🌺 Offer red flowers and Durva grass',
      '🟥 Apply Sindoor to idol',
      '🍬 Offer Modak or Ladoo',
      '🪔 Light diya and incense',
      '🙏 Chant: "Om Gam Ganapataye Namah" — 108 times',
      '🙏 Chant Ganesh Aarti: "Jai Ganesh Jai Ganesh Jai Ganesh Deva"',
      '🙇 Do Pranam (prostrate) and pray for your wish',
      '🍭 Distribute Prasad to family'
    ],
    mantra: 'ॐ गं गणपतये नमः',
    mantraRoman: 'Om Gam Ganapataye Namah',
    aarti: 'Jai Ganesh Jai Ganesh Jai Ganesh Deva, Mata Jaki Parvati Pita Mahadeva',
  },
  lakshmi: {
    name: 'Lakshmi Puja',
    deity: 'Goddess Lakshmi',
    icon: '🪷',
    purpose: 'Wealth, prosperity, business growth, financial stability',
    bestDay: 'Friday & Diwali',
    duration: '20–30 minutes',
    items: [
      'Lakshmi idol or photo',
      'Pink or white lotus flowers',
      'Kheer or sweets',
      'Coins and currency notes (to bless)',
      'Kumkum and turmeric',
      'Incense sticks',
      'Diya (ghee lamp preferred)',
      'Betel leaves and nuts',
      'Red cloth',
      'Cowrie shells'
    ],
    steps: [
      '🛁 Bathe and wear clean yellow or white clothes',
      '🧹 Clean your home thoroughly — Lakshmi resides in clean places',
      '🕯️ Place Lakshmi idol on red cloth facing East',
      '💧 Offer water in a copper vessel',
      '🌸 Offer pink or lotus flowers',
      '🟡 Apply Kumkum and turmeric to idol',
      '🍽️ Offer Kheer (sweet rice pudding) as Naivedya',
      '🪔 Light ghee lamp — it should not go out during puja',
      '🪙 Place coins near idol and pray for prosperity',
      '🙏 Chant: "Om Shreem Mahalakshmyai Namah" — 108 times',
      '🎵 Chant Lakshmi Aarti: "Om Jai Lakshmi Mata"',
      '📿 Offer betel leaves and cowrie shells',
      '🙇 Pray specifically for your financial need',
      '🍭 Distribute Prasad (Kheer)'
    ],
    mantra: 'ॐ श्रीं महालक्ष्म्यै नमः',
    mantraRoman: 'Om Shreem Mahalakshmyai Namah',
    aarti: 'Om Jai Lakshmi Mata, Maiya Jai Lakshmi Mata',
  },
  shiva: {
    name: 'Shiva Puja',
    deity: 'Lord Shiva',
    icon: '🔱',
    purpose: 'Peace, health, removing negativity, moksha, protection',
    bestDay: 'Monday & Maha Shivratri',
    duration: '15–45 minutes',
    items: [
      'Shiva Lingam or photo',
      'Bel leaves (Bilva patra) — most important',
      'Raw milk',
      'Water (Ganga Jal preferred)',
      'Honey and curd',
      'Bhasma (ash)',
      'White flowers (Dhatura, Akanda)',
      'Incense sticks',
      'Diya',
      'Rudraksha mala (for chanting)'
    ],
    steps: [
      '🛁 Bathe and wear white clothes',
      '🕐 Best time: Early morning (Brahma Muhurta) or evening',
      '💧 Pour water on Shiva Lingam first — then milk, honey, curd',
      '🌿 Offer 3 Bel leaves (bilva patra) — most sacred to Shiva',
      '⚪ Apply Bhasma (sacred ash) to Lingam',
      '🌸 Offer white flowers — never Ketaki flowers (not accepted)',
      '🪔 Light diya and incense',
      '📿 Chant "Om Namah Shivaya" 108 times on Rudraksha mala',
      '🎵 Chant Shiva Aarti: "Om Jai Shiv Omkara"',
      '🙏 Offer Bel patra with each chant if possible',
      '🙇 Pray for health, peace, or your specific need',
      '💧 Pour final offering of water',
      '🍭 Distribute Prasad (Panchamrit)'
    ],
    mantra: 'ॐ नमः शिवाय',
    mantraRoman: 'Om Namah Shivaya',
    aarti: 'Om Jai Shiv Omkara, Prabhu Jai Shiv Omkara',
  },
  durga: {
    name: 'Durga Puja / Navratri Puja',
    deity: 'Goddess Durga',
    icon: '🦁',
    purpose: 'Strength, protection, victory over enemies, courage',
    bestDay: 'Tuesday, Friday & Navratri',
    duration: '20–30 minutes',
    items: [
      'Durga Mata photo or idol',
      'Red flowers (Hibiscus/Gulhal)',
      'Red cloth',
      'Coconut',
      'Kumkum and Sindoor',
      'Chana (chickpeas) as Prasad',
      'Incense sticks',
      'Red diya (lamp)',
      'Akshat (unbroken rice)',
      'Bel leaves or Ashoka leaves'
    ],
    steps: [
      '🛁 Bathe and wear red or orange clothes',
      '🔴 Place Mata on red cloth, facing East',
      '💧 Offer water and Panchamrit',
      '🌺 Offer red hibiscus flowers — most beloved by Durga',
      '🟥 Apply Kumkum and Sindoor',
      '🥥 Break a coconut as offering',
      '🌾 Offer Akshat (rice grains)',
      '🪔 Light red diya',
      '🙏 Chant: "Om Dum Durgayai Namah" 108 times',
      '🎵 Chant Durga Chalisa or Aarti: "Jai Ambe Gauri"',
      '🙇 Pray for strength and protection from your specific challenge',
      '🍲 Offer Chana and Halwa as Prasad',
      '🍭 Distribute to 9 girls (Kanya Pujan) for maximum blessings'
    ],
    mantra: 'ॐ दुं दुर्गायै नमः',
    mantraRoman: 'Om Dum Durgayai Namah',
    aarti: 'Jai Ambe Gauri, Maiya Jai Shyama Gauri',
  },
  saraswati: {
    name: 'Saraswati Puja',
    deity: 'Goddess Saraswati',
    icon: '📚',
    purpose: 'Education, exams, creativity, arts, wisdom, eloquence',
    bestDay: 'Wednesday & Basant Panchami',
    duration: '15–20 minutes',
    items: [
      'Saraswati photo or idol',
      'White flowers (especially white lotus)',
      'Yellow clothes or flowers (on Basant Panchami)',
      'Books and instruments (to bless)',
      'White sweets (Kheer or Mishri)',
      'Incense sticks',
      'Diya',
      'Pen and notebook',
      'Kumkum',
      'Ganga Jal'
    ],
    steps: [
      '🛁 Bathe and wear yellow or white clothes',
      '📚 Place your books, notebooks, and instruments near idol for blessing',
      '🌸 Offer white lotus or white flowers',
      '💧 Sprinkle Ganga Jal on books and yourself',
      '🪔 Light diya',
      '🕯️ Light incense — preferably sandalwood',
      '🙏 Chant: "Om Aim Saraswatyai Namah" 108 times',
      '📖 Keep books open during puja — Mata will bless your knowledge',
      '🎵 Chant Saraswati Vandana: "Ya Kundendu Tushara Hara Dhavala"',
      '🍚 Offer white Kheer or Mishri',
      '🙇 Pray specifically for success in your exam or creative pursuit',
      '📖 Do not study on the actual puja day (Saraswati Puja) — give rest',
      '🍭 Distribute Prasad (white sweets)'
    ],
    mantra: 'ॐ ऐं सरस्वत्यै नमः',
    mantraRoman: 'Om Aim Saraswatyai Namah',
    aarti: 'Ya Kundendu Tushara Hara Dhavala, Ya Shubhra Vastravritha',
  },
  hanuman: {
    name: 'Hanuman Puja',
    deity: 'Lord Hanuman',
    icon: '🐒',
    purpose: 'Courage, strength, protection, clearing black magic, health',
    bestDay: 'Tuesday & Saturday',
    duration: '20–30 minutes',
    items: [
      'Hanuman photo or idol',
      'Red flowers',
      'Sindoor (red vermillion — apply to idol)',
      'Jasmine oil',
      'Ladoo (especially Boondi Ladoo)',
      'Banana',
      'Betel leaves',
      'Incense sticks',
      'Diya with mustard oil',
      'Hanuman Chalisa book'
    ],
    steps: [
      '🛁 Bathe and wear red or orange clothes',
      '🕐 Best time: Sunrise (Tuesday/Saturday)',
      '🌸 Offer red flowers to idol',
      '🟥 Apply Sindoor mixed with jasmine oil to idol — this is the most important step',
      '🍌 Offer banana and Boondi Ladoo',
      '🪔 Light mustard oil diya (not ghee)',
      '🙏 Read entire Hanuman Chalisa (40 verses)',
      '📿 Chant "Om Hanumate Namah" 108 times',
      '🎵 Chant Hanuman Aarti: "Aarti Kije Hanuman Lala Ki"',
      '🙇 Pray for courage, strength, and removal of your specific fear or obstacle',
      '🧘 End with 5-minute silent meditation',
      '🍭 Distribute Ladoo as Prasad'
    ],
    mantra: 'ॐ हनुमते नमः',
    mantraRoman: 'Om Hanumate Namah',
    aarti: 'Aarti Kije Hanuman Lala Ki, Dushta Dalan Raghunath Kala Ki',
  },
};

function getPujaGuide(deity) {
  return PUJA_GUIDES[deity.toLowerCase()] || null;
}

function getAllPujas() {
  return Object.entries(PUJA_GUIDES).map(([key, p]) => ({
    key, name: p.name, deity: p.deity, icon: p.icon, purpose: p.purpose, bestDay: p.bestDay
  }));
}

module.exports = { getPujaGuide, getAllPujas };
